language: generic
install: true
addons:
  ssh_known_hosts: hb.tuannvm.com
before_deploy:
- openssl aes-256-cbc -K $encrypted_a1cef36155ca_key -iv $encrypted_a1cef36155ca_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  - provider: script
    skip_cleanup: true
    script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/question1 root@hb.tuannvm.com:/srv/
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: ssh ubuntu@hb.tuannvm.com chmod +x /srv/question1/deploy.sh && /srv/question1/deploy.sh
    on:
      branch: develop